server:
  port: 8761

spring:
  application:
    name: discovery-service

# =========================
# EUREKA SERVER CONFIG
# =========================
eureka:
  instance:
    hostname: localhost          # hiển thị trên dashboard
  client:
    register-with-eureka: false  # không đăng ký chính nó
    fetch-registry: false        # không lấy danh sách service
  server:
    enable-self-preservation: false   # tắt chế độ tự bảo vệ khi test
    wait-time-in-ms-when-sync-empty: 0

# =========================
# ACTUATOR HEALTHCHECK (cho Docker)
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
